runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /images/harvey-os-logo.png
  static_files: static/harvey-os-logo.png
  upload: static/harvey-os-logo.png
- url: /images/harvey-os-logo-head.png
  static_files: static/harvey-os-logo-head.png
  upload: static/harvey-os-logo-head.png
- url: /styles.css
  static_files: static/styles.css
  upload: static/styles.css
- url: /.*
  script: _go_app

nobuild_files: ^(support|content)/
