application: harvey-blog
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /harvey-os-logo.png
  static_files: static/harvey-os-logo.png
  upload: static/harvey-os-logo.png
- url: /style.css
  static_files: static/style.css
  upload: static/style.css
- url: /.*
  script: _go_app

nobuild_files: ^(support|content)/
